#!/bin/bash


#eddy correct
for SUB in DTI1 DTI2 DTI3 DTI4 DTI5 DTI6 DTI7 DTI8 DTI9 DTI10 DTI11 DTI12 DTI13 DTI14 DTI15 DTI16 DTI17 DTI18 DTI19 DTI20 DTI21 DTI22 DTI23 DTI24 DTI25 DTI26 DTI27 DTI28
do
eddy_correct ${SUB}.nii.gz ${SUB}_corr.nii.gz 0
echo done eddycorrect ${SUB}

#split 4D DTI file, extract brain and create mask from first (unweighted) volume

fslsplit ${SUB}_corr.nii.gz ${SUB}DTI_ -t
bet ${SUB}DTI_0000.nii.gz ${SUB}_corr_nodif.nii.gz -m -f 0.35
rm ${SUB}DTI_00*.nii.gz

echo mask extracted ${SUB}

#do dtifit

dtifit -k ${SUB}_corr.nii.gz  -o ${SUB} -m ${SUB}_corr_nodif_mask.nii.gz -r ${SUB}.bvec -b ${SUB}.bval

echo Finished dtifit ${SUB}

done

echo Finished DTIfit, beginning TBSS

#copy FA files to folder for tbss

mkdir mytbss

cd mytbss
cp ../*FA* .

echo running tbss_1_preproc
tbss_1_preproc *.nii.gz
echo tbss_1_preproc finished 

echo running tbss_2_reg
tbss_2_reg -T
echo tbss_2_reg finished 

echo running tbss_3_postreg
tbss_3_postreg -S
echo tbss_3_postreg finished 

echo running tbss_4_prestats
tbss_4_prestats 0.2
echo tbss_4_prestats finished 


