#!/bin/bash

# Extract subject ID from dir/filename passed to script ($1)
SUB=$(echo "$1" | cut -f 2 -d '/' | cut -f 1 -d '.')

# Create analysis directory for this participant
mkdir -p anl_${SUB}

# eddy correct
eddy_correct data/${SUB}.nii.gz anl_${SUB}/${SUB}_corr.nii.gz 0
echo done eddycorrect ${SUB}

# Split 4D DTI file
fslsplit anl_${SUB}/${SUB}_corr.nii.gz anl_${SUB}/${SUB}DTI_ -t

# extract brain and create mask from first (unweighted) volume
bet anl_${SUB}/${SUB}DTI_0000.nii.gz anl_${SUB}/${SUB}_corr_nodif.nii.gz -m -f 0.35
echo mask extracted ${SUB}

# Remove temp files
rm anl_${SUB}/${SUB}DTI_00*.nii.gz

#do dtifit
dtifit -k anl_${SUB}/${SUB}_corr.nii.gz -o anl_${SUB}/${SUB} -m \
anl_${SUB}/${SUB}_corr_nodif_mask.nii.gz -r data/${SUB}.bvec -b \
data/${SUB}.bval
echo done dtifit ${SUB}

# prep for tbss
cd anl_${SUB}
mkdir -p anltbss
cd anltbss
cp ../*FA* .

# TBSS preproc: erode FA slices and zero end slices
tbss_1_preproc *.nii.gz
echo tbss_1_preproc finished 

# TBSS registration: Align each subject to standard target (FMRIB58_FA)
tbss_2_reg -T
echo tbss_2_reg finished 

# Return to working directory
cd ../..

# Place preprocessing results for subject into aggregate directory
cp -R anl_${SUB}/anltbss/* anltbss/


